Repository blank-manash/feedback, pull requests merged in 2024-09, with the labels that each got.

#5 Add CRUD for card and point
  poetry.lock
  pyproject.toml
  src/app.py
  src/constants.py
  src/persistence/__init__.py
  src/persistence/cards_helper.py
  src/persistence/models/__init__.py
  src/persistence/models/base_model.py
  src/persistence/models/card.py
  src/persistence/models/point.py
  src/persistence/points_helper.py
Labels: enhancement, Other

#7 feat(database): Create Database and Table Connections
  poetry.lock
  pyproject.toml
  src/app_test.py
  src/constants.py
  src/persistence/__init__.py
  src/persistence/base_model.py
  src/persistence/card.py
  src/persistence/cards_helper.py
  src/persistence/models/__init__.py
  src/persistence/models/base_model.py
  src/persistence/models/card.py
  src/persistence/models/point.py
  src/persistence/point.py
  src/persistence/points_helper.py
Labels: enhancement, Dependencies, Review effort [1-5]: 3

#8 fix app_test.py
  src/app_test.py
  src/constants.py
  src/persistence/card.py
Labels: enhancement, miscellaneous, Review effort [1-5]: 2

#9 Add working similar point logic in app test
  poetry.lock
  pyproject.toml
  src/app_test.py
Labels: enhancement, Dependencies, Review effort [1-5]: 3

#10 feat(backend): Backend Implementation
  .gitignore
  poetry.lock
  pyproject.toml
  src/__init__.py
  src/app.py
  src/app_test.py
  src/constants.py
  src/global_utils.py
  src/models/__init__.py
  src/models/adhoc_models.py
  src/models/creation_response.py
  src/models/similarity_response.py
  src/persistence/point.py
  src/prompts/__init__.py
  src/prompts/gemini_prompts.py
  src/router/application.py
  src/router/llm_response.py
  src/service/llm_gemini.py
  src/service/processor.py
  src/tests/__init__.py
  src/vectors/__init__.py
  src/vectors/vector_store.py
Labels: enhancement, Review effort [1-5]: 4, Bug fix
